# This is a generated file. Not intended for manual editing.
services:
  darynchat.api:
    build:
      context: "C:\\Users\\User\\RiderProjects\\DarynChat"
      dockerfile: "Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "darynchat.api:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\User\\RiderProjects\\DarynChat:/app:rw"
    - "C:\\Users\\User\\RiderProjects\\DarynChat:/src:rw"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\User\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\User\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_7_29_11_13_00:/var/opt/rider-debugger:rw"
    working_dir: "/app"
